# Tensorflow Eager Execution
*Source: https://www.tensorflow.org/guide/eager*

In [1]:
import tensorflow as tf

In [2]:
tf.enable_eager_execution()

In [3]:
tf.executing_eagerly()

True

In [4]:
x = [[2.]]
m = tf.matmul(x, x)

print("hello, {}".format(m))

hello, [[4.]]


In [5]:
a = tf.constant([[1,2],[3,4]])

print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [6]:
b = tf.add(a,1)

print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [7]:
print(a*b)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [8]:
print(a+b)

tf.Tensor(
[[3 5]
 [7 9]], shape=(2, 2), dtype=int32)


In [9]:
import numpy as np

c = np.multiply(a, b)
print(c)

[[ 2  6]
 [12 20]]


In [12]:
print(a)

print("====")

print(a.numpy())

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
====
[[1 2]
 [3 4]]


In [16]:
def fizzbuzz(max_num):
    counter = tf.constant(0)
    max_num = tf.convert_to_tensor(max_num)
    
    for num in range(1, max_num.numpy()+1):
        num = tf.constant(num)
        if int(num % 3) == 0 and int(num % 5) == 0:
            print('FizzBuzz')
        if int(num % 3) == 0:
            print('Fizz')
        if int(num % 5) == 0:
            print('Buzz')
        else:
            print(num.numpy())
        counter += 1

In [17]:
fizzbuzz(15)

1
2
Fizz
3
4
Buzz
Fizz
6
7
8
Fizz
9
Buzz
11
Fizz
12
13
14
FizzBuzz
Fizz
Buzz
