In [22]:
import numpy as np

In [37]:
arr = np.array([1,2,3,4]).reshape(2,2)
arr

array([[1, 2],
       [3, 4]])

In [40]:
arr2 = np.array([(1,2),(3,4)])
arr2

array([[1, 2],
       [3, 4]])

In [41]:
arr * arr2

array([[ 1,  4],
       [ 9, 16]])

In [42]:
arr + arr2

array([[2, 4],
       [6, 8]])

In [44]:
arr.dot(arr2)

array([[ 7, 10],
       [15, 22]])

In [45]:
arr[:,1]

array([2, 4])

In [46]:
arr[:,0]

array([1, 3])

In [56]:
three_d = np.array((1,2,3,4,5,6,7,8)).reshape(2,2,2)

In [57]:
three_d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [58]:
three_d[:,:,0]

array([[1, 3],
       [5, 7]])

In [59]:
three_d[1,:,0]

array([5, 7])

In [60]:
three_d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [61]:
three_d.size

8

In [62]:
three_d.reshape(8)

array([1, 2, 3, 4, 5, 6, 7, 8])